### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [dr1s/prometheus_metrics#2]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.1.6.5. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary prometheus-metrics -w /tmp/ext prometheus-metrics==0.1.6.5
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting prometheus-metrics==0.1.6.5
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/d92/adc8d350204e7/prometheus_metrics-0.1.6.5.tar.gz (3.7 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-q0dgqzvo/prometheus-metrics/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-q0dgqzvo/prometheus-metrics/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-q0dgqzvo/prometheus-metrics/pip-egg-info
         cwd: /tmp/pip-wheel-q0dgqzvo/prometheus-metrics/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-q0dgqzvo/prometheus-metrics/setup.py", line 9, in <module>
        with open('requirements.txt', 'r') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by dr1s** [comment]
Fixed, but I would recommend using this library anyway. Its kind of a mess and hasn't been touched in a while.

**Comment by thatch** [comment]
sounds good.
